### ISSUE TITLE
nvidia-smi: not found

### ISSUE THREAD

**Issue by junqiang0718** [kata-containers/kata-containers#10457]
Create a container and specify the GPU card
`
root@node1:~# ctr --debug run --rm --runtime "io.containerd.kata.v2" --device /dev/vfio/222 -t "docker.io/nvidia/cuda:12.4.0-base-ubuntu20.04" demo bash
DEBU[0000] remote introspection plugin filters           filters="[type==io.containerd.snapshotter.v1, id==overlayfs]"
root@:/# nvidia-smi
bash: nvidia-smi: command not found
`
Check the GPU card in the virtual machine
`
root@node1:~# kata-runtime exec demo
root@localhost:/# 
root@localhost:/# 
root@localhost:/# 
root@localhost:/# nvidia-smi 
Thu Oct 24 02:45:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A5000               Off | 00000000:02:00.0 Off |                  Off |
| 30%   31C    P0              N/A / 230W |      0MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
`
The nvidia-container-toolkit log is as follows
`
root@localhost:/# cat /run/nvidia-container-toolkit.log 

-- WARNING, the following logs are for debugging purposes only --

I1024 02:45:35.928811 141 nvc.c:393] initializing library context (version=1.16.2, build=921e2f3197385173cf8670342e96e98afe9b3dd3)
I1024 02:45:35.928869 141 nvc.c:364] using root /
I1024 02:45:35.928871 141 nvc.c:365] using ldcache /etc/ld.so.cache
I1024 02:45:35.928873 141 nvc.c:366] using unprivileged user 65534:65534
I1024 02:45:35.928883 141 nvc.c:410] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I1024 02:45:35.928964 141 nvc.c:412] dxcore initialization failed, continuing assuming a non-WSL environment
I1024 02:45:35.930432 156 nvc.c:278] loading kernel module nvidia
I1024 02:45:35.930516 156 nvc.c:282] running mknod for /dev/nvidiactl
E1024 02:45:35.930543 156 nvc.c:284] could not create kernel module device node
I1024 02:45:35.930545 156 nvc.c:286] running mknod for /dev/nvidia0
E1024 02:45:35.930566 156 nvc.c:288] could not create kernel module device node
I1024 02:45:35.930568 156 nvc.c:290] running mknod for all nvcaps in /dev/nvidia-caps
I1024 02:45:35.934243 156 nvc.c:218] running mknod for /dev/nvidia-caps/nvidia-cap1 from /proc/driver/nvidia/capabilities/mig/config
E1024 02:45:35.934301 156 nvc.c:292] could not create kernel module device nodes: error running mknod for nvcap: /proc/driver/nvidia/capabilities/mig/config
I1024 02:45:35.934303 156 nvc.c:301] loading kernel module nvidia_uvm
I1024 02:45:35.934310 156 nvc.c:305] running mknod for /dev/nvidia-uvm
E1024 02:45:35.934334 156 nvc.c:307] could not create kernel module device node
I1024 02:45:35.934337 156 nvc.c:310] loading kernel module nvidia_modeset
I1024 02:45:35.938496 156 nvc.c:314] running mknod for /dev/nvidia-modeset
E1024 02:45:35.938523 156 nvc.c:316] could not create kernel module device node
I1024 02:45:35.938704 160 rpc.c:71] starting driver rpc service
I1024 02:45:36.647578 164 rpc.c:71] starting nvcgo rpc service
I1024 02:45:36.649528 141 nvc_container.c:240] configuring container with 'compute utility supervised'
I1024 02:45:36.657881 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libcuda.so.550.54.15
I1024 02:45:36.658385 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libcudadebugger.so.550.54.15
I1024 02:45:36.658860 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-nvvm.so.550.54.15
I1024 02:45:36.658906 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-pkcs11-openssl3.so.550.54.15
I1024 02:45:36.658922 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-pkcs11.so.550.54.15
I1024 02:45:36.659388 141 nvc_container.c:88] selecting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-ptxjitcompiler.so.550.54.15
I1024 02:45:36.659919 141 nvc_container.c:262] setting pid to 138
I1024 02:45:36.659928 141 nvc_container.c:263] setting rootfs to /run/kata-containers/demo/rootfs
I1024 02:45:36.659931 141 nvc_container.c:264] setting owner to 0:0
I1024 02:45:36.659934 141 nvc_container.c:265] setting bins directory to /usr/bin
I1024 02:45:36.659937 141 nvc_container.c:266] setting libs directory to /usr/lib/x86_64-linux-gnu
I1024 02:45:36.659940 141 nvc_container.c:267] setting libs32 directory to /usr/lib/i386-linux-gnu
I1024 02:45:36.659943 141 nvc_container.c:268] setting cudart directory to /usr/local/cuda
I1024 02:45:36.659946 141 nvc_container.c:269] setting ldconfig to @/sbin/ldconfig.real (host relative)
I1024 02:45:36.659949 141 nvc_container.c:270] setting mount namespace to /proc/138/ns/mnt
I1024 02:45:36.659951 141 nvc_container.c:272] detected cgroupv1
I1024 02:45:36.659954 141 nvc_container.c:273] setting devices cgroup to /sys/fs/cgroup/devices/default/demo
I1024 02:45:36.659969 141 nvc_info.c:799] requesting driver information with ''
I1024 02:45:36.663647 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.535.146.02
I1024 02:45:36.663748 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.535.146.02
I1024 02:45:36.663808 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.535.146.02
I1024 02:45:36.663846 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.535.146.02
I1024 02:45:36.663888 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.535.146.02
I1024 02:45:36.663952 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.535.146.02
I1024 02:45:36.663996 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.535.146.02
I1024 02:45:36.664040 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.146.02
I1024 02:45:36.664093 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.535.146.02
I1024 02:45:36.664149 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.535.146.02
I1024 02:45:36.664237 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.535.146.02
I1024 02:45:36.664294 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.535.146.02
I1024 02:45:36.664353 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.535.146.02
I1024 02:45:36.664462 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libcudadebugger.so.535.146.02
I1024 02:45:36.664490 141 nvc_info.c:175] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.535.146.02
W1024 02:45:36.664540 141 nvc_info.c:403] missing library libnvidia-nscq.so
W1024 02:45:36.664545 141 nvc_info.c:403] missing library libnvidia-gpucomp.so
W1024 02:45:36.664548 141 nvc_info.c:403] missing library libnvidia-fatbinaryloader.so
W1024 02:45:36.664551 141 nvc_info.c:403] missing library libnvidia-compiler.so
W1024 02:45:36.664554 141 nvc_info.c:403] missing library libnvidia-ngx.so
W1024 02:45:36.664556 141 nvc_info.c:403] missing library libnvidia-eglcore.so
W1024 02:45:36.664559 141 nvc_info.c:403] missing library libnvidia-glcore.so
W1024 02:45:36.664562 141 nvc_info.c:403] missing library libnvidia-tls.so
W1024 02:45:36.664564 141 nvc_info.c:403] missing library libnvidia-glsi.so
W1024 02:45:36.664567 141 nvc_info.c:403] missing library libnvidia-ifr.so
W1024 02:45:36.664570 141 nvc_info.c:403] missing library libnvidia-rtcore.so
W1024 02:45:36.664572 141 nvc_info.c:403] missing library libnvoptix.so
W1024 02:45:36.664575 141 nvc_info.c:403] missing library libGLX_nvidia.so
W1024 02:45:36.664578 141 nvc_info.c:403] missing library libEGL_nvidia.so
W1024 02:45:36.664580 141 nvc_info.c:403] missing library libGLESv2_nvidia.so
W1024 02:45:36.664583 141 nvc_info.c:403] missing library libGLESv1_CM_nvidia.so
W1024 02:45:36.664586 141 nvc_info.c:403] missing library libnvidia-glvkspirv.so
W1024 02:45:36.664588 141 nvc_info.c:403] missing library libnvidia-cbl.so
W1024 02:45:36.664591 141 nvc_info.c:407] missing compat32 library libnvidia-ml.so
W1024 02:45:36.664594 141 nvc_info.c:407] missing compat32 library libnvidia-cfg.so
W1024 02:45:36.664597 141 nvc_info.c:407] missing compat32 library libnvidia-nscq.so
W1024 02:45:36.664599 141 nvc_info.c:407] missing compat32 library libcuda.so
W1024 02:45:36.664602 141 nvc_info.c:407] missing compat32 library libcudadebugger.so
W1024 02:45:36.664605 141 nvc_info.c:407] missing compat32 library libnvidia-opencl.so
W1024 02:45:36.664607 141 nvc_info.c:407] missing compat32 library libnvidia-gpucomp.so
W1024 02:45:36.664610 141 nvc_info.c:407] missing compat32 library libnvidia-ptxjitcompiler.so
W1024 02:45:36.664613 141 nvc_info.c:407] missing compat32 library libnvidia-fatbinaryloader.so
W1024 02:45:36.664616 141 nvc_info.c:407] missing compat32 library libnvidia-allocator.so
W1024 02:45:36.664618 141 nvc_info.c:407] missing compat32 library libnvidia-compiler.so
W1024 02:45:36.664621 141 nvc_info.c:407] missing compat32 library libnvidia-pkcs11.so
W1024 02:45:36.664624 141 nvc_info.c:407] missing compat32 library libnvidia-pkcs11-openssl3.so
W1024 02:45:36.664626 141 nvc_info.c:407] missing compat32 library libnvidia-nvvm.so
W1024 02:45:36.664632 141 nvc_info.c:407] missing compat32 library libnvidia-ngx.so
W1024 02:45:36.664635 141 nvc_info.c:407] missing compat32 library libvdpau_nvidia.so
W1024 02:45:36.664638 141 nvc_info.c:407] missing compat32 library libnvidia-encode.so
W1024 02:45:36.664640 141 nvc_info.c:407] missing compat32 library libnvidia-opticalflow.so
W1024 02:45:36.664643 141 nvc_info.c:407] missing compat32 library libnvcuvid.so
W1024 02:45:36.664646 141 nvc_info.c:407] missing compat32 library libnvidia-eglcore.so
W1024 02:45:36.664648 141 nvc_info.c:407] missing compat32 library libnvidia-glcore.so
W1024 02:45:36.664651 141 nvc_info.c:407] missing compat32 library libnvidia-tls.so
W1024 02:45:36.664654 141 nvc_info.c:407] missing compat32 library libnvidia-glsi.so
W1024 02:45:36.664656 141 nvc_info.c:407] missing compat32 library libnvidia-fbc.so
W1024 02:45:36.664659 141 nvc_info.c:407] missing compat32 library libnvidia-ifr.so
W1024 02:45:36.664662 141 nvc_info.c:407] missing compat32 library libnvidia-rtcore.so
W1024 02:45:36.664664 141 nvc_info.c:407] missing compat32 library libnvoptix.so
W1024 02:45:36.664667 141 nvc_info.c:407] missing compat32 library libGLX_nvidia.so
W1024 02:45:36.664669 141 nvc_info.c:407] missing compat32 library libEGL_nvidia.so
W1024 02:45:36.664672 141 nvc_info.c:407] missing compat32 library libGLESv2_nvidia.so
W1024 02:45:36.664675 141 nvc_info.c:407] missing compat32 library libGLESv1_CM_nvidia.so
W1024 02:45:36.664677 141 nvc_info.c:407] missing compat32 library libnvidia-glvkspirv.so
W1024 02:45:36.664680 141 nvc_info.c:407] missing compat32 library libnvidia-cbl.so
I1024 02:45:36.664909 141 nvc_info.c:301] selecting /usr/bin/nvidia-smi
I1024 02:45:36.664927 141 nvc_info.c:301] selecting /usr/bin/nvidia-debugdump
I1024 02:45:36.664944 141 nvc_info.c:301] selecting /usr/bin/nvidia-persistenced
I1024 02:45:36.664969 141 nvc_info.c:301] selecting /usr/bin/nvidia-cuda-mps-control
I1024 02:45:36.664985 141 nvc_info.c:301] selecting /usr/bin/nvidia-cuda-mps-server
W1024 02:45:36.665010 141 nvc_info.c:429] missing binary nv-fabricmanager
I1024 02:45:36.665093 141 nvc_info.c:489] listing firmware path /lib/firmware/nvidia/535.146.02/gsp_ga10x.bin
I1024 02:45:36.665098 141 nvc_info.c:489] listing firmware path /lib/firmware/nvidia/535.146.02/gsp_tu10x.bin
W1024 02:45:36.665128 141 nvc_info.c:325] missing device /dev/nvidia-uvm-tools
I1024 02:45:36.665133 141 nvc_info.c:562] listing device /dev/nvidiactl
I1024 02:45:36.665136 141 nvc_info.c:562] listing device /dev/nvidia-uvm
I1024 02:45:36.665139 141 nvc_info.c:562] listing device /dev/nvidia-modeset
W1024 02:45:36.665157 141 nvc_info.c:351] missing ipc path /var/run/nvidia-persistenced/socket
W1024 02:45:36.665171 141 nvc_info.c:351] missing ipc path /var/run/nvidia-fabricmanager/socket
W1024 02:45:36.665183 141 nvc_info.c:351] missing ipc path /tmp/nvidia-mps
I1024 02:45:36.665187 141 nvc_info.c:855] requesting device information with ''
I1024 02:45:36.671216 141 nvc_info.c:746] listing device /dev/nvidia0 (GPU-c0676c33-99d7-1714-288f-7d7868fdd482 at 00000000:02:00.0)
I1024 02:45:36.671761 141 nvc_mount.c:370] mounting tmpfs at /run/kata-containers/demo/rootfs/proc/driver/nvidia
W1024 02:45:36.672423 141 utils.c:547] The path /run/kata-containers/demo/rootfs/usr/bin already exists with the required mode; skipping create
I1024 02:45:36.673292 141 nvc_mount.c:90] mounting /usr/bin/nvidia-smi at /run/kata-containers/demo/rootfs/usr/bin/nvidia-smi with flags 0x7
I1024 02:45:36.673687 141 nvc_mount.c:90] mounting /usr/bin/nvidia-debugdump at /run/kata-containers/demo/rootfs/usr/bin/nvidia-debugdump with flags 0x7
I1024 02:45:36.674040 141 nvc_mount.c:90] mounting /usr/bin/nvidia-persistenced at /run/kata-containers/demo/rootfs/usr/bin/nvidia-persistenced with flags 0x7
I1024 02:45:36.674657 141 nvc_mount.c:90] mounting /usr/bin/nvidia-cuda-mps-control at /run/kata-containers/demo/rootfs/usr/bin/nvidia-cuda-mps-control with flags 0x7
I1024 02:45:36.675112 141 nvc_mount.c:90] mounting /usr/bin/nvidia-cuda-mps-server at /run/kata-containers/demo/rootfs/usr/bin/nvidia-cuda-mps-server with flags 0x7
W1024 02:45:36.675338 141 utils.c:547] The path /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu already exists with the required mode; skipping create
I1024 02:45:36.675947 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.146.02 with flags 0x7
I1024 02:45:36.676353 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.535.146.02 with flags 0x7
I1024 02:45:36.676796 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libcuda.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libcuda.so.535.146.02 with flags 0x7
I1024 02:45:36.677192 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libcudadebugger.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libcudadebugger.so.535.146.02 with flags 0x7
I1024 02:45:36.677574 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.535.146.02 with flags 0x7
I1024 02:45:36.677973 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.535.146.02 with flags 0x7
I1024 02:45:36.678354 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.535.146.02 with flags 0x7
I1024 02:45:36.695328 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.535.146.02 with flags 0x7
I1024 02:45:36.695866 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.535.146.02 with flags 0x7
I1024 02:45:36.696338 141 nvc_mount.c:90] mounting /usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.535.146.02 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.535.146.02 with flags 0x7
I1024 02:45:36.696437 141 nvc_mount.c:531] creating symlink /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
W1024 02:45:36.696676 141 utils.c:547] The path /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu already exists with the required mode; skipping create
I1024 02:45:36.697065 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libcuda.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libcuda.so.550.54.15 with flags 0x7
I1024 02:45:36.697528 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libcudadebugger.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libcudadebugger.so.550.54.15 with flags 0x7
I1024 02:45:36.697990 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-nvvm.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.550.54.15 with flags 0x7
I1024 02:45:36.698455 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-pkcs11-openssl3.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.550.54.15 with flags 0x7
I1024 02:45:36.698918 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-pkcs11.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.550.54.15 with flags 0x7
I1024 02:45:36.699424 141 nvc_mount.c:90] mounting /run/kata-containers/demo/rootfs/usr/local/cuda-12.4/compat/libnvidia-ptxjitcompiler.so.550.54.15 at /run/kata-containers/demo/rootfs/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.550.54.15 with flags 0x7
I1024 02:45:36.700970 141 nvc_mount.c:90] mounting /lib/firmware/nvidia/535.146.02/gsp_ga10x.bin at /run/kata-containers/demo/rootfs/usr/lib/firmware/nvidia/535.146.02/gsp_ga10x.bin with flags 0x7
I1024 02:45:36.701615 141 nvc_mount.c:90] mounting /lib/firmware/nvidia/535.146.02/gsp_tu10x.bin at /run/kata-containers/demo/rootfs/usr/lib/firmware/nvidia/535.146.02/gsp_tu10x.bin with flags 0x7
I1024 02:45:36.701819 141 nvc_mount.c:234] mounting /dev/nvidiactl at /run/kata-containers/demo/rootfs/dev/nvidiactl
I1024 02:45:36.705819 141 nvc.c:452] shutting down library context
I1024 02:45:36.705883 164 rpc.c:95] terminating nvcgo rpc service
I1024 02:45:36.706327 141 rpc.c:135] nvcgo rpc service terminated successfully
I1024 02:45:36.812823 160 rpc.c:95] terminating driver rpc service
I1024 02:45:36.812911 141 rpc.c:135] driver rpc service terminated successfully
`

An error appeared in the log
`
E1024 02:45:35.930543 156 nvc.c:284] could not create kernel module device node
E1024 02:45:35.930566 156 nvc.c:288] could not create kernel module device node
E1024 02:45:35.934301 156 nvc.c:292] could not create kernel module device nodes: error running mknod for nvcap: /proc/driver/nvidia/capabilities/mig/config
E1024 02:45:35.934334 156 nvc.c:307] could not create kernel module device node
E1024 02:45:35.938523 156 nvc.c:316] could not create kernel module device node
`
Please help me to solve this problem, thank you

**Comment by junqiang0718** [comment]
The kata.log log is as follows：
[kata.log](https://github.com/user-attachments/files/17500403/kata.log)

**Comment by Apokleos** [comment]
cc @zvonkok

**Comment by junqiang0718** [comment]
The following error log appears when creating and using the dragonball container:
`{"msg":"wait on container terminated","level":"INFO","ts":"2024-10-24T14:54:39.292817556Z","container_id":"cuda","subsystem":"virt-container","component":"runtimes","name":"kata-runtime","source":"cuda","pid":"1738378","version":"0.1.0"}
{"msg":"container terminated","level":"INFO","ts":"2024-10-24T14:54:39.292967445Z","container_id":"cuda","source":"cuda","name":"kata-runtime","pid":"1738378","version":"0.1.0","subsystem":"virt-container","component":"runtimes"}
{"msg":"{\"msg\":\"receive createcontainer, storages: [Storage { driver: \\\"ephemeral\\\", driver_options: [], source: \\\"shm\\\", fstype: \\\"tmpfs\\\", options: [\\\"noexec\\\", \\\"nosuid\\\", \\\"nodev\\\", \\\"mode=1777\\\", \\\"size=67108864\\\"], mount_point: \\\"/run/kata-containers/sandbox/shm\\\", fs_group: MessageField(None), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }]\",\"level\":\"INFO\",\"ts\":\"2024-10-24T14:54:39.249698335Z\",\"version\":\"0.1.0\",\"pid\":\"120\",\"source\":\"agent\",\"name\":\"kata-agent\",\"subsystem\":\"rpc\"}","level":"INFO","ts":"2024-10-24T14:54:39.293286729Z","component":"agent","name":"kata-runtime","version":"0.1.0","source":"cuda","subsystem":"agent","pid":"1738378"}
{"msg":"{\"msg\":\"device-id: 31f9bf0b891c213, device-type: vfio-pci-gk, device-vm-path: , device-container-path: /dev/vfio/222, device-options: [\\\"0000:d1:00.0=\\\", \\\"0000:d1:00.1=01\\\"]\",\"level\":\"INFO\",\"ts\":\"2024-10-24T14:54:39.249765521Z\",\"pid\":\"120\",\"source\":\"agent\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"subsystem\":\"rpc\"}","level":"INFO","ts":"2024-10-24T14:54:39.29352684Z","version":"0.1.0","source":"cuda","component":"agent","subsystem":"agent","pid":"1738378","name":"kata-runtime"}
{"msg":"{\"msg\":\"failed to add devices, error: cannot parse integer from empty string\\n\\nStack backtrace:\\n   0: <unknown>\\n   1: <unknown>\\n   2: <unknown>\\n   3: <unknown>\\n   4: <unknown>\\n   5: <unknown>\\n   6: <unknown>\\n   7: <unknown>\\n   8: <unknown>\\n   9: <unknown>\\n  10: <unknown>\\n  11: <unknown>\\n  12: <unknown>\\n  13: <unknown>\\n  14: <unknown>\\n  15: <unknown>\\n  16: <unknown>\",\"level\":\"ERRO\",\"ts\":\"2024-10-24T14:54:39.250174857Z\",\"pid\":\"120\",\"subsystem\":\"rpc\",\"source\":\"agent\",\"version\":\"0.1.0\",\"name\":\"kata-agent\"}","level":"ERRO","ts":"2024-10-24T14:54:39.293794472Z","name":"kata-runtime","pid":"1738378","subsystem":"agent","source":"cuda","component":"agent","version":"0.1.0"}
{"msg":"{\"msg\":\"rpc call from shim to agent: \\\"remove_container\\\"\",\"level\":\"INFO\",\"ts\":\"2024-10-24T14:54:39.252388365Z\",\"pid\":\"120\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"source\":\"agent\",\"subsystem\":\"rpc\"}","level":"INFO","ts":"2024-10-24T14:54:39.294010577Z","subsystem":"agent","version":"0.1.0","source":"cuda","pid":"1738378","component":"agent","name":"kata-runtime"}
{"msg":"stop container: agent remove container failed: rpc status: Status { code: INTERNAL, message: \"Invalid container id\\n\\nStack backtrace:\\n   0: <unknown>\\n   1: <unknown>\\n   2: <unknown>\\n   3: <unknown>\\n   4: <unknown>\\n   5: <unknown>\\n   6: <unknown>\\n   7: <unknown>\", details: [], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }","level":"WARN","ts":"2024-10-24T14:54:39.294181772Z","container_id":"cuda","source":"cuda","subsystem":"virt-container","name":"kata-runtime","pid":"1738378","component":"runtimes","version":"0.1.0"}`

**Comment by zvonkok** [comment]
@junqiang0718 I am pushing some new PRs to make GPU consumption far more easier with Kata. What kind of GPU do you have? Looks like an RTX judging that you have a multi-function-device `0000:d1:00.0`=GPU `0000:d1:00.1`=Audio. 

Are you running with Dragonball and runtime-rs?

**Comment by Apokleos** [comment]
> What kind of GPU do you have? Looks like an RTX judging that you have a multi-function-device `0000:d1:00.0`=GPU `0000:d1:00.1`=Audio.
> 
@zvonkok Yes It's NVIDIA RTX A5000, but with kata-runtime.
>
> Are you running with Dragonball and runtime-rs?
>
And he has a try with runtime-rs with dragonball but also failed with  multifunction scenarios. I am thinking how to address such problems.

**Comment by gongchangsui** [comment]
Did you install [nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) in guestOS?

**Comment by gongchangsui** [comment]
I've had this problem too.
I installed the nvidia driver and nvidia-container-toolkit in guestOS, and added the hook script for prestart according to the documentation. The rootfs and guest kernel are made based on the 6.6.0 kernel, and the architecture is aarch64.
I can't find /run/nvidia-container-toolkit.log in guestOS.
How do I check where the problem is? Thank you

**Comment by junqiang0718** [comment]
@gongchangsui 
/run/nvidia-container-toolkit.log 
This is the log path configured in the nvidia-container-toolkit configuration file, which is not enabled by default.
`root@localhost:/# cat /etc/nvidia-container-runtime/config.toml 
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
debug = "/run/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig.real"
load-kmods = true
no-cgroups = true
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"

[nvidia-container-runtime]
debug = "/run/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.cdi]
annotation-prefixes = ["cdi.k8s.io/"]
default-kind = "nvidia.com/gpu"
spec-dirs = ["/etc/cdi", "/var/run/cdi"]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"

[nvidia-container-runtime-hook]
path = "nvidia-container-runtime-hook"
skip-mode-detection = false

[nvidia-ctk]
path = "nvidia-ctk"`

**Comment by Apokleos** [comment]
> I've had this problem too. I installed the nvidia driver and nvidia-container-toolkit in guestOS, and added the hook script for prestart according to the documentation. The rootfs and guest kernel are made based on the 6.6.0 kernel, and the architecture is aarch64. I can't find /run/nvidia-container-toolkit.log in guestOS. How do I check where the problem is? Thank you
>
You are using the released kata-3.10.0 with kata-runtime/qemu VMM ?

**Comment by Apokleos** [comment]
> > I've had this problem too. I installed the nvidia driver and nvidia-container-toolkit in guestOS, and added the hook script for prestart according to the documentation. The rootfs and guest kernel are made based on the 6.6.0 kernel, and the architecture is aarch64. I can't find /run/nvidia-container-toolkit.log in guestOS. How do I check where the problem is? Thank you
> 
@gongchangsui You are using the released kata-3.10.0 with kata-runtime/qemu VMM ?

**Comment by VeniZhang** [comment]
@Apokleos Thank you for your answer.  I used kata-3.10.0 with kata-runtime/qemu VMM.

**Comment by VeniZhang** [comment]
> @gongchangsui /run/nvidia-container-toolkit.log This is the log path configured in the nvidia-container-toolkit configuration file, which is not enabled by default. `root@localhost:/# cat /etc/nvidia-container-runtime/config.toml #accept-nvidia-visible-devices-as-volume-mounts = false #accept-nvidia-visible-devices-envvar-when-unprivileged = true disable-require = false supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video" #swarm-resource = "DOCKER_RESOURCE_GPU"
> 
> [nvidia-container-cli] debug = "/run/nvidia-container-toolkit.log" environment = [] #ldcache = "/etc/ld.so.cache" ldconfig = "@/sbin/ldconfig.real" load-kmods = true no-cgroups = true #path = "/usr/bin/nvidia-container-cli" #root = "/run/nvidia/driver" #user = "root:video"
> 
> [nvidia-container-runtime] debug = "/run/nvidia-container-runtime.log" log-level = "info" mode = "auto" runtimes = ["docker-runc", "runc"]
> 
> [nvidia-container-runtime.modes]
> 
> [nvidia-container-runtime.modes.cdi] annotation-prefixes = ["cdi.k8s.io/"] default-kind = "nvidia.com/gpu" spec-dirs = ["/etc/cdi", "/var/run/cdi"]
> 
> [nvidia-container-runtime.modes.csv] mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"
> 
> [nvidia-container-runtime-hook] path = "nvidia-container-runtime-hook" skip-mode-detection = false
> 
> [nvidia-ctk] path = "nvidia-ctk"`

Thank you for your answer.

**Comment by gongchangsui** [comment]
> @gongchangsui /run/nvidia-container-toolkit.log This is the log path configured in the nvidia-container-toolkit configuration file, which is not enabled by default. `root@localhost:/# cat /etc/nvidia-container-runtime/config.toml #accept-nvidia-visible-devices-as-volume-mounts = false #accept-nvidia-visible-devices-envvar-when-unprivileged = true disable-require = false supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video" #swarm-resource = "DOCKER_RESOURCE_GPU"
> 
> [nvidia-container-cli] debug = "/run/nvidia-container-toolkit.log" environment = [] #ldcache = "/etc/ld.so.cache" ldconfig = "@/sbin/ldconfig.real" load-kmods = true no-cgroups = true #path = "/usr/bin/nvidia-container-cli" #root = "/run/nvidia/driver" #user = "root:video"
> 
> [nvidia-container-runtime] debug = "/run/nvidia-container-runtime.log" log-level = "info" mode = "auto" runtimes = ["docker-runc", "runc"]
> 
> [nvidia-container-runtime.modes]
> 
> [nvidia-container-runtime.modes.cdi] annotation-prefixes = ["cdi.k8s.io/"] default-kind = "nvidia.com/gpu" spec-dirs = ["/etc/cdi", "/var/run/cdi"]
> 
> [nvidia-container-runtime.modes.csv] mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"
> 
> [nvidia-container-runtime-hook] path = "nvidia-container-runtime-hook" skip-mode-detection = false
> 
> [nvidia-ctk] path = "nvidia-ctk"`

Thank you for your answer.

**Comment by gongchangsui** [comment]
> > > I've had this problem too. I installed the nvidia driver and nvidia-container-toolkit in guestOS, and added the hook script for prestart according to the documentation. The rootfs and guest kernel are made based on the 6.6.0 kernel, and the architecture is aarch64. I can't find /run/nvidia-container-toolkit.log in guestOS. How do I check where the problem is? Thank you
> 
> @gongchangsui You are using the released kata-3.10.0 with kata-runtime/qemu VMM ?

Thank you for your answer. Yes,  the kata version is 3.10.0. The kernel is compiled by me without any patch and installed in the rootfs made by me. (The script for making rootfs will report an error when executed. [error](https://github.com/kata-containers/kata-containers/issues/10450)) What other steps do I need to take?

**Comment by Apokleos** [comment]
Thx @junqiang0718 for giving us helpful solution.

**Comment by gongchangsui** [comment]
@Apokleos  @junqiang0718  Hi， how to resolve this bug？I don't see any solution.

**Comment by junqiang0718** [comment]
@gongchangsui  There are two problems. The first one is that nvidia-smi cannot be seen. The reason is that kata has upgraded to cgroupv2 version. It is necessary to change the nvidia-container-toolkit configuration, no-cgroups = true. The second problem is that the default timeout of kata processing hook is 10s. If 7 cards are used, the time will exceed 10s due to hot plugging. So the kata code was changed to increase the timeout to 60s, and the 7 card problem was solved.

**Comment by gongchangsui** [comment]
> --- a/src/libs/kata-sys-util/src/hooks.rs +++ b/src/libs/kata-sys-util/src/hooks.rs @@ -16,7 +16,7 @@ use subprocess::{ExitStatus, Popen, PopenConfig, PopenError, Redirection}; use crate::validate::valid_env; use crate::{eother, sl};
> 
> -const DEFAULT_HOOK_TIMEOUT_SEC: i32 = 10; +const DEFAULT_HOOK_TIMEOUT_SEC: i32 = 60;
> 
> @gongchangsui go

@junqiang0718 Thank you for reply.  I set  `no-cgroups = true` in `/etc/nvidia-container-runtime/config.toml` and set `DEFAULT_HOOK_TIMEOUT_SEC: i32 = 60;`. But there are still three questions:
    1. nvidia-smi still not found,
    2. the log is not found. 
    3. the hook script of prestart not run.
How to solve this problem? Thank you.
```
bash-5.2# cat /etc/nvidia-container-runtime/config.toml 
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
debug = "/var/log/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig"
load-kmods = true
no-cgroups = true
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"

[nvidia-container-runtime]
debug = "/var/log/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc", "crun"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.cdi]
annotation-prefixes = ["cdi.k8s.io/"]
default-kind = "nvidia.com/gpu"
spec-dirs = ["/etc/cdi", "/var/run/cdi"]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"

[nvidia-container-runtime-hook]
path = "nvidia-container-runtime-hook"
skip-mode-detection = false

[nvidia-ctk]
path = "nvidia-ctk"

```
```
bash-5.2# cat /usr/share/oci/hooks/prestart/nvidia-container-toolkit.sh 
#!/bin/bash -x
/bin/touch /home/test
/usr/bin/nvidia-container-toolkit -debug $@

```

**Comment by junqiang0718** [comment]
@gongchangsui Please show us your run command.

**Comment by gongchangsui** [comment]
> @gongchangsui Please show us your run command.

@junqiang0718  Thank you for reply. 
```
# after modify DEFAULT_HOOK_TIMEOUT_SEC: i32 = 60;
make -C src/libs
make -C src/runtime

SECCOMP=no CFLAGS=-mno-outline-atomics ./rootfs.sh -r "$PWD/kata-overlay"

# rootfs is mount rootfs.img
cp -rf kata-overlay/etc/systemd/system/basic.target.wants/  rootfs/etc/systemd/system/ 
cp -rf kata-overlay/etc/systemd/system/kata-containers.target.wants  rootfs/etc/systemd/system/ 
cp -rf kata-overlay/usr/lib/systemd/system/*  rootfs/usr/lib/systemd/system/ 
cp -rf kata-overlay/usr/bin/kata-agent  rootfs/usr/bin

# run container 
ctr run --runtime "io.containerd.kata.v2"   --device /dev/vfio/86  -t  --rm docker.io/library/other-vllm-model:entry-bash  other-vllm
```

**Comment by junqiang0718** [comment]
@gongchangsui After adding vfio device, nvidia-smi is seen in the container, indicating that nvidia-container-toolkit has run successfully. However, the path configuration should be configured as /run/nvidia-container-toolkit.log to see it. Not all paths have write permissions.

**Comment by junqiang0718** [comment]
@gongchangsui 
/usr/bin/nvidia-container-cli --load-kmods --debug=/dev/stderr configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility  --pid=123 /run/kata-containers/cuda/rootfs
Use this command to debug【Failed to initialize NVML: Unknown Error】

**Comment by gongchangsui** [comment]
@junqiang0718  Thank you very much.  The output as following. I install cuda in container.   Should I install cuda in gutest os according the output?  
```
I1029 06:18:28.878685 1457 nvc.c:393] initializing library context (version=1.16.2, build=921e2f3197385173cf8670342e96e98afe9b3dd3)
I1029 06:18:28.878784 1457 nvc.c:364] using root /
I1029 06:18:28.878788 1457 nvc.c:365] using ldcache /etc/ld.so.cache
I1029 06:18:28.878790 1457 nvc.c:366] using unprivileged user 65534:65534
I1029 06:18:28.878819 1457 nvc.c:410] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I1029 06:18:28.878874 1457 nvc.c:412] dxcore initialization failed, continuing assuming a non-WSL environment
I1029 06:18:28.880826 1458 nvc.c:278] loading kernel module nvidia
I1029 06:18:28.881266 1458 nvc.c:282] running mknod for /dev/nvidiactl
I1029 06:18:28.881503 1458 nvc.c:286] running mknod for /dev/nvidia0
I1029 06:18:28.881555 1458 nvc.c:290] running mknod for all nvcaps in /dev/nvidia-caps
I1029 06:18:28.886567 1458 nvc.c:218] running mknod for /dev/nvidia-caps/nvidia-cap1 from /proc/driver/nvidia/capabilities/mig/config
I1029 06:18:28.886977 1458 nvc.c:218] running mknod for /dev/nvidia-caps/nvidia-cap2 from /proc/driver/nvidia/capabilities/mig/monitor
I1029 06:18:28.889036 1458 nvc.c:301] loading kernel module nvidia_uvm
I1029 06:18:28.889085 1458 nvc.c:305] running mknod for /dev/nvidia-uvm
I1029 06:18:28.889193 1458 nvc.c:310] loading kernel module nvidia_modeset
I1029 06:18:28.889212 1458 nvc.c:314] running mknod for /dev/nvidia-modeset
I1029 06:18:28.890786 1459 rpc.c:71] starting driver rpc service
I1029 06:18:29.836080 1470 rpc.c:71] starting nvcgo rpc service
I1029 06:18:29.839331 1457 nvc_container.c:240] configuring container with 'compute utility supervised'
nvidia-container-cli: container error: open failed: /proc/123/root/run/kata-containers/cuda/rootfs: no such file or directory
I1029 06:18:29.839450 1457 nvc.c:452] shutting down library context
I1029 06:18:29.839606 1470 rpc.c:95] terminating nvcgo rpc service
I1029 06:18:29.841530 1457 rpc.c:135] nvcgo rpc service terminated successfully
I1029 06:18:29.997344 1459 rpc.c:95] terminating driver rpc service
I1029 06:18:29.998350 1457 rpc.c:135] driver rpc service terminated successfully

```

> @gongchangsui /usr/bin/nvidia-container-cli --load-kmods --debug=/dev/stderr configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --pid=123 /run/kata-containers/cuda/rootfs Use this command to debug【Failed to initialize NVML: Unknown Error】

**Comment by gongchangsui** [comment]
> @gongchangsui After adding vfio device, nvidia-smi is seen in the container, indicating that nvidia-container-toolkit has run successfully. However, the path configuration should be configured as /run/nvidia-container-toolkit.log to see it. Not all paths have write permissions.

@junqiang0718 Thank you again.  I changed the log path to `/run/nvidia-container-toolkit.log`, but still not found the log.
```
bash-5.2# cat /etc/nvidia-container-runtime/config.toml 
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
debug = "/run/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig"
load-kmods = true
no-cgroups = true
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"

[nvidia-container-runtime]
debug = "/run/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc", "crun"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.cdi]
annotation-prefixes = ["cdi.k8s.io/"]
default-kind = "nvidia.com/gpu"
spec-dirs = ["/etc/cdi", "/var/run/cdi"]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"

[nvidia-container-runtime-hook]
path = "nvidia-container-runtime-hook"
skip-mode-detection = false

[nvidia-ctk]
path = "nvidia-ctk"

```
![image](https://github.com/user-attachments/assets/cb6a6ca5-7826-4995-8129-ae8f950522cf)

**Comment by junqiang0718** [comment]
@gongchangsui In an environment where the log path is not visible, does the container also not see nvidia-smi? By the way, let us see the environment variables in the container.

**Comment by junqiang0718** [comment]
@gongchangsui Logs viewed in guest（/run/nvidia-container-toolkit.log）

**Comment by gongchangsui** [comment]
> @gongchangsui Logs viewed in guest（/run/nvidia-container-toolkit.log）
The log is not found in guest OS and container.

**Comment by gongchangsui** [comment]
> @gongchangsui In an environment where the log path is not visible, does the container also not see nvidia-smi? By the way, let us see the environment variables in the container.

@junqiang0718 Thank you for your reply.  Tht container can see nvidia-smi.  But  there is `Failed to initialize NVML: Unknown Error` when I run nvidia-smi.    I run nvidia-smi in guest OS work well.  [debug that error](https://github.com/kata-containers/kata-containers/issues/10457#issuecomment-2443319217)
