### ISSUE TITLE
CI failure for trusted storage with guest OS Ubuntu 22.04 on s390x

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#10838]
# Description of problem

Since we bumped the guest OS from 20.04 to 22.04 (see #10794), the following CI jobs has started failing:

- `Test we can pull an image inside the guest using trusted storage`
- `Test we can pull a large image inside the guest with large createcontainer timeout`

due to the following:

```
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   Scheduled              2m6s                default-scheduler  Successfully assigned kata-containers-k8s-tests/large-image-pod to a314lp42
  Normal   SuccessfulMountVolume  2m6s                kubelet            MapVolume.MapPodDevice succeeded for volume "trusted-block-pv" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/trusted-block-pv"
  Normal   SuccessfulMountVolume  2m6s                kubelet            MapVolume.MapPodDevice succeeded for volume "trusted-block-pv" volumeMapPath "/var/lib/kubelet/pods/33057fe6-9ea0-4515-b0ce-8d1a70c77b1d/volumeDevices/kubernetes.io~local
-volume"
  Normal   Pulled                 38s (x5 over 2m1s)  kubelet            Container image "ghcr.io/confidential-containers/test-container:rust-1.79.0" already present on machine
  Normal   Created                38s (x5 over 2m)    kubelet            Created container app-container
  Warning  Failed                 38s (x5 over 2m)    kubelet            Error: failed to create containerd task: failed to create shim task: rpc status: Status { code: INTERNAL, message: "[CDH] [ERROR]: secure mount failed", details: [], spec
ial_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
```

We have to figure out a root cause and resolve the issue soon.

@hbrueckner

**Comment by ryansavino** [comment]
Seeing the same thing with initrd for qemu-snp. I've disabled the same tests for now for qemu-snp. I have a feeling it's not related to MEASURED_ROOTFS being turned off, but more with something in the 22.04 upgrade, but I could be wrong. Maybe @ChengyuZhu6 has some thoughts here?

**Comment by sprt** [comment]
I'm not familiar with image storage - @ChengyuZhu6 probably knows more

**Comment by fitzthum** [comment]
This is an interesting part of the logs from the SNP test. Not sure if it's the same for s390x. https://github.com/kata-containers/kata-containers/actions/runs/13480300728/job/37679880201?pr=10803#step:10:4146

Unable to mount the block device for some reason.

**Comment by BbolroC** [comment]
> This is an interesting part of the logs from the SNP test. Not sure if it's the same for s390x. https://github.com/kata-containers/kata-containers/actions/runs/13480300728/job/37679880201?pr=10803#step:10:4146
> 
> Unable to mount the block device for some reason.

yeah, same error 😉

**Comment by manuelh-dev** [comment]
@BbolroC @ryansavino @fitzthum @sprt (CC @mythi) - I can't access the logs here anymore but this looks like something I can across yesterday. 
Looking at https://github.com/kata-containers/kata-containers/pull/12396, specifically this commit: https://github.com/kata-containers/kata-containers/pull/12396/changes/3e1065205f356c47e4f5b59942c61310f31cfc00

Please take a look at the commit message. Chances are, this is exactly that issue. I think, after merging this PR we may be able to remove some of the skips in this test

**Comment by BbolroC** [comment]
> Please take a look at the commit message. Chances are, this is exactly that issue. I think, after merging this PR we may be able to remove some of the skips in this test

Thanks for the heads-up. I will look into it and run the skipped tests and update the issue. 😉

**Comment by BbolroC** [comment]
> > Please take a look at the commit message. Chances are, this is exactly that issue. I think, after merging this PR we may be able to remove some of the skips in this test
> 
> Thanks for the heads-up. I will look into it and run the skipped tests and update the issue. 😉

I'll get started on this as soon as the bug you reported [here](https://katacontainers.slack.com/archives/C879ACQ00/p1770339312890159) on Slack is fixed. Thanks!

**Comment by manuelh-dev** [comment]
@BbolroC - thank you! The bug reported here actually turns out to be an issue with Kata CI caching, as far as I could see. So, you're good to go.

Here's my current state:
- the user space components to run these tests should be present now as we gate things with CONFIDENTIAL_GUEST: https://github.com/kata-containers/kata-containers/commit/976df22119b1f26866b308658432c252f313f80c
- what may still be missing is to adapt tools\packaging\static-build\kernel\build.sh with a similar gate:
```
if [[ "${MEASURED_ROOTFS}" == "yes" ]]; then
	kernel_builder_args+=" -m"
fi
```
If the tests still fail, we may be missing kernel support and we also need to gate against `CONFIDENTIAL_GUEST`.
- I have started a feature branch (draft PR) for these tests; my first step was to ease the nydus condition to also exercise the tests for the force-guest pull method: https://github.com/kata-containers/kata-containers/pull/12461
  - I *just added* (edited) a commit here real quick to enable the relevant tests. I added you to the draft PR.

**Comment by BbolroC** [comment]
@manuelh-dev got an error for `Test we can pull an image inside the guest using trusted storage`:

```
Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   Scheduled              25s               default-scheduler  Successfully assigned kata-containers-k8s-tests/large-image-pod to a46lp22.lnxne.boe
  Normal   SuccessfulMountVolume  25s               kubelet            MapVolume.MapPodDevice succeeded for volume "trusted-block-pv" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/trusted-block-pv"
  Normal   SuccessfulMountVolume  25s               kubelet            MapVolume.MapPodDevice succeeded for volume "trusted-block-pv" volumeMapPath "/var/lib/kubelet/pods/f89a896f-8571-4d11-a013-866561151f85/volumeDevices/kubernetes.io~local-volume"
  Normal   Pulled                 4s (x3 over 19s)  kubelet            Container image "ghcr.io/confidential-containers/test-container:rust-1.79.0" already present on machine
  Normal   Created                4s (x3 over 19s)  kubelet            Created container: app-container
  Warning  Failed                 3s (x3 over 18s)  kubelet            Error: failed to create containerd task: failed to create shim task: failed to handle trusted storage: rpc status: Status { code: INTERNAL, message: "[CDH] [ERROR]: Secure Mount failed", details: [], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
```

I was wondering if you are aware that the issue was raised when `MEASURED_ROOTFS` is set to `no` on s390x. Here is a history for you:

1. Introduced trusted storage with Ubuntu 20.04 base image for rootfs: all tests passed on s390x (`MEASURED_ROOTFS=yes`, see #9999)
2. Bumped the base image to 22.04: got some tests to fail due to `MEASURED_ROOTFS=yes`
3. Set `MEASURED_ROOTFS` to `no` for s390x: tests for trusted storages started failing -> decided to skip the tests affected (#10841)

In the meantime, the guest image was updated to 24.04.

Unfortunately, I didn't have time to revisit the issue quite a while. I will put this on my to-do list for this year. 😉

**Comment by manuelh-dev** [comment]
Thanks, @BbolroC , in the meantime I have opened [PR 12461](https://github.com/kata-containers/kata-containers/pull/12461). I was also able to run the tests successfully on a local TDX machine. The CI runner for TDX still shows/showed failures, so I have increased their timeouts. It is possible that we need to increase the node's kubelet `runtimeRequestTimeout` to make the test pass. If the runner is configured with the default timeout of 120 seconds, this may not be enough time to pull the container image and get the container from 'created' to 'started' state in time.

**Comment by BbolroC** [comment]
> I have opened https://github.com/kata-containers/kata-containers/pull/12461.

Thanks for the heads-up. Just let me know when the PR is ready for merge. I will run the tests on my SEL machine again.

**Comment by fidencio** [comment]
> Thanks, [@BbolroC](https://github.com/BbolroC) , in the meantime I have opened [PR 12461](https://github.com/kata-containers/kata-containers/pull/12461). I was also able to run the tests successfully on a local TDX machine. The CI runner for TDX still shows/showed failures, so I have increased their timeouts. It is possible that we need to increase the node's kubelet `runtimeRequestTimeout` to make the test pass. If the runner is configured with the default timeout of 120 seconds, this may not be enough time to pull the container image and get the container from 'created' to 'started' state in time.

Note to self, when moving from AKS to the free runners, I should also consider adding such timeout to avoid issues.

**Comment by fidencio** [comment]
> > Thanks, [@BbolroC](https://github.com/BbolroC) , in the meantime I have opened [PR 12461](https://github.com/kata-containers/kata-containers/pull/12461). I was also able to run the tests successfully on a local TDX machine. The CI runner for TDX still shows/showed failures, so I have increased their timeouts. It is possible that we need to increase the node's kubelet `runtimeRequestTimeout` to make the test pass. If the runner is configured with the default timeout of 120 seconds, this may not be enough time to pull the container image and get the container from 'created' to 'started' state in time.
> 
> Note to self, when moving from AKS to the free runners, I should also consider adding such timeout to avoid issues.

https://github.com/kata-containers/kata-containers/commit/40a2f38b1eb4baf68a03224b9b308bb78dacad0a

**Comment by manuelh-dev** [comment]
Folks, thanks for merging https://github.com/kata-containers/kata-containers/pull/12461 - @BbolroC - fine to close the issue (if so, please go ahead) :)

**Comment by BbolroC** [comment]
Still seeing test failures with rust-runtime `qemu-se-runtime-rs`. (log: https://github.com/kata-containers/kata-containers/actions/runs/22294055360/job/64495295419#step:3:13848 I tested only with go-runtime `qemu-se`). Let me figure out what led to the failure. Thanks!

**Comment by BbolroC** [comment]
It seems the tests failed due to `qemu-se-runtime-rs` not supporting block device hotplug, which will be resolved by https://github.com/kata-containers/kata-containers/pull/12531. I will make it merged soon. Thanks!

---

Update: I've checked the failed tests are successfully passed for `qemu-se-runtime-rs` with the PR, meaning I will close this issue after #12531 is merged. Thanks!
