### ISSUE TITLE
cri-o does not work in kata-containers 2.2.0: Failed to create pod sandbox: rpc error: code = Unknown desc = dial unix /run/containerd/s/a554844d06959beb34922f4e5411c5ff380d2f72e2d9505d406109cebcc8bc5d: connection refused

### ISSUE THREAD

**Issue by jclab-joseph** [kata-containers/kata-containers#2611]
Link https://github.com/kubernetes/kubernetes/issues/104929

# Description of problem

When I create a pod through kata in kubernetes configured with cri-o, the pod is not created.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true
  runtimeClassName: kata-qemu
```

```
Sep 11 02:50:10 k8s-ci-node-05102 kubelet[751]: /run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa: connect: connection refused
Sep 11 02:50:10 k8s-ci-node-05102 kubelet[751]: /run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa: connect: connection refused
Sep 11 02:50:10 k8s-ci-node-05102 kubelet[751]: /run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa: connect: connection refused
Sep 11 02:50:10 k8s-ci-node-05102 kubelet[751]: E0911 02:50:10.986267     751 pod_workers.go:191] Error syncing pod 4796973e-8f3a-4830-9101-1f197541da71 ("nginx_default(4796973e-8f3a-4830-9101-1f197541da71)"), skipping: failed to "CreatePodSandbox" for "nginx_default(4796973e-8f3a-4830-9101-1f197541da71)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx_default(4796973e-8f3a-4830-9101-1f197541da71)\" failed: rpc error: code = Unknown desc = dial unix \x00/run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa: connect: connection refused"
```

# More informations

**/usr/local/bin/containerd-shim-kata-v2**:
```
#!/bin/sh
/snap/bin/kata-containers.shim "$@"
```

# kata-collect

https://gist.github.com/jclab-joseph/7444ca1f9a3d23f285a48d9635a230ae

**Comment by jclab-joseph** [comment]
```
root     3767551  0.1  0.0 1326128 10960 ?       Sl   03:38   0:03 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id fa4583d778683e16b44ce589fe255f49e36fba427865364e090e86e3ab7f86c8
root     3767774  0.0  0.0 1327536 11432 ?       Sl   03:38   0:01 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 59026b3305dd32c8056728aed15b885d74d01f269b0fc16e3286cc57f0a7c29f
root     3767995  0.1  0.0 1401268 10848 ?       Sl   03:38   0:03 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 289b773a32cd26780d4a865be6a2191ad331c327bdca378f44eca25fe96a898b
root     3770051  0.2  0.0 1327536 11156 ?       Sl   03:40   0:04 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id bc9ddec506241db9d6cf34d8049cdb49243bff2faad249f6a9b23b472a844a9d
root     3784924  0.1  0.0 1327536 11136 ?       Sl   03:53   0:02 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 7884d54a06fb3bd34ee8d949bb4b7387134de76023e59b97062f0fd3f79c3ed7
root     3786763  2.4  0.0 1326128 10836 ?       Sl   03:55   0:27 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id a065556223423cbf3d4dad5fcf931e3f445f203f4612feff141779110d011228
root     3787594  0.0  0.0 1327536 11156 ?       Sl   03:56   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id dc202ad39d5ba3ec5084ffe4ff1066dde1c2c2b909d2493341d6acd815e6bad8
root     3789403  0.0  0.0 1326128 11636 ?       Sl   03:59   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id b1d869154726c23d63e2ffeab3cbc306db440c0166d1ef91ea242f679fd8b6fa
root     3790363  0.0  0.0 1327536 11052 ?       Sl   04:00   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 0d46de791e1e9df591e3107a692391318035637827ae92933650df168746cd7a
root     3790655  0.0  0.0 1326128 10916 ?       Sl   04:01   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 429f91ace7c4b45414ae0060ad5199bb0bee508f20aea5ca6fc05bf79b44e12f
root     3790879  0.0  0.0 1253804 11064 ?       Sl   04:01   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 5503255bf075b3744209d9e6a7eb4a91352df411ece648ec60a948a8a4958996
root     3791172  0.0  0.0 1327536 11348 ?       Sl   04:01   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id d68974de6fee1d128936bea280252e7cc544510376afd3b01124e40d5f885244
root     3791469  0.1  0.0 1327536 11576 ?       Sl   04:02   0:01 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 97dcaa4460a67bb441957ccd20c9956afea0bdd9b5b5d7e5f98fb256ecdc4da2
root     3792643  0.2  0.0 1327536 11144 ?       Sl   04:03   0:01 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 638dc40aaf1a0ef234a8180056a33fb42cd0289094c007d57440fd2700e07c7d
root     3794182  0.1  0.0 1327536 11012 ?       Sl   04:04   0:00 /snap/kata-containers/901/usr/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id ef7cc67ae772efd5586bc851634199ebae0a670140f4b5e77dfb08d0a7270e09
```

Additionally, the containerd-shim-kata-v2 process doesn't die, crashing the host machine...

**Comment by devimc** [comment]
@jclab-joseph does kata 2.1 was working?

**Comment by jclab-joseph** [comment]
@devimc This issue is after upgrading kata to 2.2.0 in #2467
In 2.1, issue #2467 occurs.

**Comment by devimc** [comment]
this looks like a problem with kubelet:

Sep 11 02:50:10 k8s-ci-node-05102 kubelet[751]: E0911 02:50:10.986267     751 pod_workers.go:191] Error syncing pod 4796973e-8f3a-4830-9101-1f197541da71 ("nginx_default(4796973e-8f3a-4830-9101-1f197541da71)"), skipping: failed to "CreatePodSandbox" for "nginx_default(4796973e-8f3a-4830-9101-1f197541da71)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx_default(4796973e-8f3a-4830-9101-1f197541da71)\" failed: rpc error: code = Unknown desc = dial unix \x00/run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa: connect: connection refused"

we don't have any file called `pod_workers.go` also  path to containerd socket looks incorrect`dial unix \x00/run/containerd/s/a613e1e8bdab5137886078fbc47bd0159066e7b7ed19f5f4a6620cb5343dc4aa`, if you are using kubeadm to setup your cluster make sure you are using this option `--container-runtime-endpoint=unix:///run/containerd/containerd.sock"`

**Comment by fidencio** [comment]
Taking a look at your CRI-O configuration:
```
[crio.runtime.runtimes.kata-fc] --> This will NOT work with kata-containers 2.x
runtime_path = "/snap/bin/kata-containers.runtime"
runtime_type = "oci"
runtime_root = ""

[crio.runtime.runtimes.kata-qemu] --> This look reasonable
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"

[crio.runtime.runtimes.kata-runtime] --> You'd be better with the one above
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = ""
```

There was a spam of errors on CRI-O due to the update of the vendored containerd on the kata-containers side, but those were harmless (scary, but still harmless).

I wonder whether the snap related config was done correctly.

**Comment by jclab-joseph** [comment]
Currently, instead of snap, I tried to install it directly according to the method of https://github.com/kata-containers/kata-containers/issues/2467#issuecomment-917876818, but it is the same.

**Comment by c3d** [comment]
@fgiudici Would you mind assigning this one to yourself (or find someone who could follow up)? Thanks.

**Comment by fgiudici** [comment]
> @fgiudici Would you mind assigning this one to yourself (or find someone who could follow up)? Thanks.

@c3d , I cannot assign issues, missing superpowers ;-)
Guess the issue comes from a combination of the latest kata shimv2 and an "old" cri-o release (cri-o 1.18).
https://github.com/cri-o/cri-o/issues/5276 should be solved first, than the fix may be backported (but I don't think that is what causing the pod to not start).
Not sure anyway that shimv2 is supported in cri-o 1.18. I would at least use cri-o 1.19.

**Comment by jclab-joseph** [comment]
@fgiudici @c3d 

Thank you for your efforts to solve the problem.
Now this issue is the same in cri-o 1.19.2.

```
NAME                    STATUS     ROLES    AGE      VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
.................       Ready      <none>   28d      v1.19.14   x.x.x.x    <none>        Ubuntu 20.04.2 LTS   5.4.0-81-generic     cri-o://1.19.2

```

**Comment by fgiudici** [comment]
Thanks @jclab-joseph, cri-o 1.19.2 should work with shimv2. I will look into kata with cri-o 1.19.2  (also if I may not be that quick).
@c3d , feel free to assign this to me.

**Comment by jclab-joseph** [comment]
@fgiudici 
The previous issue almost certainly seems to happen when running on a virtual machine rather than a physical machine.
Perhaps this issue is also due to the virtual machine.
I use Proxmox (based on kvm qemu).

**Comment by git-noise** [comment]
Hello,

For info I am also seeing the same issue in a nested virtualization scenario.Using kata-containers latest/stable: 2.2.2 installed via snap.
What confuses me is that kata looks for containerd path while I am using cri-o.

Although it has its own issue, latest/candidate: 2.1.0 does not produce the same error and works with cri-o.

Many thanks,

**Comment by fgiudici** [comment]
Hey, thanks for the report.
Kata 2.2.x is not working with CRI-O due to some issues related to cgroups management.
After 2.2.x was branched a rework on cgroups management has been merged and the pod creation is no more an issue.
There are still issues however on how the cgroups are created when systemd cgroups driver is used (see #2868): the plan is to put effort in the main branch to fix systemd cgroups driver for the 2.3.x releases.
There is no plan to fix the issue in 2.2.x that I am aware of. Target for this is the next release.

**Comment by git-noise** [comment]
Thanks a lot for the info. I'll follow the main branch, build and report if I can - it may not be immediate though.

**Comment by git-noise** [comment]
Hello,

Quick update that this issue seems to still be present with snap latest/edge, which seems to be 2.3 branch.
```
kata-runtime  : 2.3.0-rc0
   commit   : b192d388c1e2b0b612df14a3476df36d08682475
   OCI specs: 1.0.2-dev
```
Am I missing something? I'll still try to build from source when I can.

Best,

**Comment by fidencio** [comment]
@git-noise, folks are still working on that, please, follow: https://github.com/kata-containers/kata-containers/pull/2959

**Comment by git-noise** [comment]
@fidencio my mistake, I thought it was a related but separated issue, and that the container should at least start.
Many thanks will follow and revert then.

Best

**Comment by fidencio** [comment]
@git-noise, I am just cutting a 2.3.0-rc1 release in a few hours, you may want to use that depending on the containerd version you'll use.

**Comment by git-noise** [comment]
@fidencio Thanks I will pay attention and update as soon a I see it. I am using cri-o though, should i also use this one?

**Comment by fidencio** [comment]
I *think* CRI-O should be fine if you're using `sandbox_cgroup_only=false` on your configuration.
I just cut the release, in an hour or so the new binaries should be available.

**Comment by fidencio** [comment]
> I _think_ CRI-O should be fine if you're using `sandbox_cgroup_only=false` on your kata-containers configuration. I just cut the release, in an hour or so the new binaries should be available.

**Comment by git-noise** [comment]
ok great, let me try to install it manually, snap does not seem to display that last version yet.

**Comment by git-noise** [comment]
@fidencio Hello, so I just built and installed the latest:
```
kata-runtime  : 2.3.0-rc1
   commit   : <<unknown>>
   OCI specs: 1.0.2-dev
```

And with in my configuration.toml:
```
sandbox_cgroup_only=false
```
Sadly I still see the same containerd error - while I am actually using cri-o
```
Failed to create pod sandbox: rpc error: code = Unknown desc = dial unix /run/containerd/s/f5...................
```
Let me know if I can provide anything else.

Best,

**Comment by fidencio** [comment]
@git-noise, please, provide me your CRI-O configuration file.

As we hit a last minute issue on "rc1", I'll be mostly focused on the "rc2" release Today, but would be nice to at least see all your configuration files.

**Comment by git-noise** [comment]
@fidencio. Of course. So this is the crio.conf snippet where I defined kata:
```
# Kata Containers with the QEMU VMM
[crio.runtime.runtimes.kata-qemu]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
```
And ```/usr/local/bin/containerd-shim-kata-v2``` is either the binary from the github/tar build, or a simlink to snapd binaries, depending if its built locally or installed from snap. Right now its from the rc1:
```
/usr/local/bin/containerd-shim-kata-v2:
  Version:  1.5.7+unknown
  Revision: 
  Go version: go1.17.3
```

Finally cri-o version is ```1.20.5~0```


Hope it helps and many thanks for your help again.

**Comment by fidencio** [comment]
So, @snir911 landed some patches Today on the stable-2.3 branch which will be part of the `2.3.0`release (to be cut in a week from now) that most likely will help this case.
@git-noise, would be possible for you to give it a try building from the `stable-2.3` branch?

**Comment by git-noise** [comment]
@fidencio
I just did and I sadly see the exact same behavior which is:
```
Nov 16 00:10:57 kube-node kubelet[900]: E1116 00:10:57.491189     900 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "my-app-7ff85848d6-c7hdr_my-app(63e196ed-c1ac-43a4-9dae-2072d24fd08d)" failed: rpc error: code = Unknown desc = dial unix
Nov 16 00:10:57 kube-node kubelet[900]: E1116 00:10:57.491205     900 kuberuntime_manager.go:755] createPodSandbox for pod "my-app-7ff85848d6-c7hdr_my-app(63e196ed-c1ac-43a4-9dae-2072d24fd08d)" failed: rpc error: code = Unknown desc = dial unix
Nov 16 00:10:57 kube-node kubelet[900]: E1116 00:10:57.491288     900 pod_workers.go:191] Error syncing pod 63e196ed-c1ac-43a4-9dae-2072d24fd08d ("my-app-7ff85848d6-c7hdr_my-app(63e196ed-c1ac-43a4-9dae-2072d24fd08d)"), skipping: failed to "CreatePodSandbox" for "my-app-7ff85848d6-c7hdr_my-app(63e196ed-c1ac-43a4-9dae-2072d24fd08d)" with CreatePodSandboxError: "CreatePodSandbox for pod \"my-app-7ff85848d6-c7hdr_my-app(63e196ed-c1ac-43a4-9dae-2072d24fd08d)\" failed: rpc error: code = Unknown desc = dial unix \x00/run/containerd/s/f0a6d2be650d82ceb75442bcbe729763babb5c6b84b38461717deae0348f6d50: connect: connection refused"
```
To rebuild this one I got an issue with go that would not download the src in selecting branch-mode, so I just cloned the repo, checked out the stable-2.3 branch and did a classic:
```
make
make && sudo -E PATH=$PATH make install
```
It showed ```kata-runtime - version 2.3.0-rc0 (commit b046c1ef6bbd675ca9f4430572345137b3df6935)``` is that normal?

**Comment by git-noise** [comment]
@fidencio

Hello,
Just reporting back, I just retried the latest release 2.3 via snap and I am still encountering the same issue.
```
kata-runtime  : 2.3.0
   commit   : 185f96d1706a15a091f532cb1410071e545937d5
   OCI specs: 1.0.2-dev
```

**Comment by Wang-Kai** [comment]
> @fidencio
> 
> Hello, Just reporting back, I just retried the latest release 2.3 via snap and I am still encountering the same issue.
> 
> ```
> kata-runtime  : 2.3.0
>    commit   : 185f96d1706a15a091f532cb1410071e545937d5
>    OCI specs: 1.0.2-dev
> ```

I luckily installed it, i hope can help you .

K8s version
```console
k version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

CRI-O version

```console
crio --version

crio version 1.23.0
Version:          1.23.0
GitCommit:        9b7f5ae815c22a1d754abfbc2890d8d4c10e240d
GitTreeState:     clean
BuildDate:        2021-12-21T21:38:22Z
GoVersion:        go1.17.5
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  true
```
kata version

```console
kata-runtime version
kata-runtime  : 2.3.1
   commit   : 365e358115824beb055a64767dc23c46dfcd8813
   OCI specs: 1.0.2-dev
```

crio.conf

```
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
```

**Comment by git-noise** [comment]
Thanks @Wang-Kai, I am afraid it is still not working for me - although I am using ```crio version 1.20.6```. Are you deploying on a bare metal or virtualized cluster?

@fidencio at this point I will try to redeploy on another cluster, possibly with containerd, to try to pinpoint if it's cri-o, containerd, virtualization of something else related. I am still a bit confused why we are seeing ```/run/containerd/``` related path in a ```crio-o``` installation.

**Comment by fgiudici** [comment]
> @fidencio at this point I will try to redeploy on another cluster, possibly with containerd, to try to pinpoint if it's cri-o, containerd, virtualization within VM or something else related. I am still a bit confused why we are seeing `/run/containerd/` related path in a `crio-o` installation.

Yep, this seems to hint an issue in Kubernetes (kubelet) configuration (as suggested in https://github.com/kata-containers/kata-containers/issues/2611#issuecomment-918132057).
The errors comes from the kubelet code (kuberuntime_sandbox.go & pod_workers.go).
Wondering... what is the reported container runtime in:
`kubectl get nodes -o wide` ?

**Comment by Wang-Kai** [comment]
> 

I deployed it on a bare metal.

**Comment by Wang-Kai** [comment]
> 

I deployed it on a bare metal.

**Comment by Wang-Kai** [comment]
> Thanks @Wang-Kai, I am afraid it is still not working for me - although I am using `crio version 1.20.6`. Are you deploying on a bare metal or virtualized cluster?
> 
> @fidencio at this point I will try to redeploy on another cluster, possibly with containerd, to try to pinpoint if it's cri-o, containerd, virtualization within VM or something else related. I am still a bit confused why we are seeing `/run/containerd/` related path in a `crio-o` installation.

I deployed it on a bare metal.

**Comment by git-noise** [comment]
@fgiudici
Sorry for the delay, I digged deeper on the history of these nodes. It seems at one point they used containerd and then were switched to cri-o.
Not seeing any ref to containerd anymore in the config files - and cri-o seems to be used indeed as changing its config has an impact or even running ```sudo kubectl get nodes -o wide``` as you asked shows ```cri-o://1.20.6```.
But I definitely see ```/run/containerd/storage``` still being used by something somehow, so I guess that's where the issue comes from.

So is that some remnant of containerd on the nodes, or something conflicting relating to virtualized nodes somehow, no real clue. As I mentioned I'll do a clean deployment, but may take me some time - and report back.

Thanks for your patient help!

**Comment by git-noise** [comment]
> @fgiudici Sorry for the delay, I digged deeper on the history of these nodes. It seems at one point they used containerd and then were switched to cri-o. Not seeing any ref to containerd anymore in the config files - and cri-o seems to be used indeed as changing its config has an impact or even running `sudo kubectl get nodes -o wide` as you asked shows `cri-o://1.20.6`. But I definitely see `/run/containerd/storage` still being used by something somehow, so I guess that's where the issue comes from.
> 
> So is that some remnant of containerd on the nodes, or something conflicting relating to virtualized nodes somehow, no real clue. As I mentioned I'll do a clean deployment, but may take me some time - and report back.
> 
> Thanks for your patient help!

Actually these are still created and used by ```/snap/kata-containers/1979/usr/bin/containerd-shim-kata-v2```.
So is it normal for kata to write things in the ```/run/containerd/s/``` with a cri-o runtime?

**Comment by fgiudici** [comment]
> > @fgiudici Sorry for the delay, I digged deeper on the history of these nodes. It seems at one point they used containerd and then were switched to cri-o. Not seeing any ref to containerd anymore in the config files - and cri-o seems to be used indeed as changing its config has an impact or even running `sudo kubectl get nodes -o wide` as you asked shows `cri-o://1.20.6`. But I definitely see `/run/containerd/storage` still being used by something somehow, so I guess that's where the issue comes from.
> > So is that some remnant of containerd on the nodes, or something conflicting relating to virtualized nodes somehow, no real clue. As I mentioned I'll do a clean deployment, but may take me some time - and report back.
> > Thanks for your patient help!
> 
> Actually these are still created and used by `/snap/kata-containers/1979/usr/bin/containerd-shim-kata-v2`. So is it normal for kata to write things in the `/run/containerd/s/` with a cri-o runtime?

Hey @git-noise, no, it is not normal. Looks weird and honestly it looks to me a config/setup issue.
May I ask you which distro are you using and how did you deployed kubernetes?

**Comment by mark-au** [comment]
@git-noise I believe this is crio related.
I've not traced it to a specific commit but I saw this same problem with 1.20.7 and if I change only the crio binary to 1.21.6  it goes away. Note that I still see the sockets created under /run/containerd/s but there's no longer an error.

Sorry to not give you a root cause but felt it was worth sharing. I saw the same `\x00/run/containerd/s/` in my logfile, maybe there's an extra prefix char there in crio

**Comment by jclab-joseph** [comment]
working now
- kata-container : v3.0.0 & v3.0.1
- kubernetes : v1.19.16
- Ubuntu : 22.04.1 LTS
- Containerd : 1.5.9-0ubuntu3.1
- Kernel : 5.15.0-56-generic

```
$ ls -al /dev/loop*
brw-rw---- 1 root disk  7,   0 Dec 28 07:08 /dev/loop0
brw-rw---- 1 root disk  7,   1 Dec 15 03:13 /dev/loop1
brw-rw---- 1 root disk  7,   2 Dec 15 03:13 /dev/loop2
brw-rw---- 1 root disk  7,   3 Dec 15 03:13 /dev/loop3
brw-rw---- 1 root disk  7,   4 Dec 15 03:13 /dev/loop4
brw-rw---- 1 root disk  7,   5 Dec 28 07:08 /dev/loop5
brw-rw---- 1 root disk  7,   6 Dec 15 03:13 /dev/loop6
brw-rw---- 1 root disk  7,   7 Dec 15 03:13 /dev/loop7
crw-rw---- 1 root disk 10, 237 Dec 15 03:13 /dev/loop-control
```
